### PR TITLE
updated nuget-references to b32.1

### PR DESCRIPTION
**Pull request by joreg**
this now builds for me out of the box with SD5 beta5:
- open Solution
- Make sure Build config is set to: x86
- run: Restore Packages
- Build

(for some reason a Rebuild does not run, but the Build does).

### CODE REVIEW

**Comment by joreg** [comment]
wait...that still does not seem to be the whole story..

**Comment by smakhtin** [comment]
Don't get it. Can you explain please?

**Comment by joreg** [comment]
while this works on the PC i edited it, i tried on another and get a lot of errors again. i am doing this all with SharpDevelop that still seems to have troubles with nugets...i am on it..

**Comment by joreg** [comment]
ok. this now works like a charm. tested on different PCs with SharpDevelop 5 (beta5) and VisualStudio 2013, both with nuget 2.8.x

**Pull request merged**
