### PR TITLE
Small filters fixes, new filter node

### PR DESCRIPTION
**Pull request by smakhtin**
Added WithInRange filter for HSV filtering. Also, fixed inputs on GT,LT,EQ nodes, so now it's in vvvv style (from 0 to 1). 

As side effect, added HSV8 and HSV32F color formats into Utils section.

### CODE REVIEW

**Comment by elliotwoods** [comment]
i can't automatically merge this PR right now as it conflicts with the current master branch.
the refactoring is a bit tricky as it affects so many files.
can we please section off small sets of changes into local (in your fork) feature branches, and make PR's with them.

alternatively i can go through and do the merge manually.
there's lots of changes in here which i'll need to change my own patches in response to also.

**Comment by elliotwoods** [comment]
could you make a list of the features which are to be merged from there?

So far we have
1. WithinRange HSV support
2. HSV color formats
3. Normalised range support for GT, LT, EQ nodes
4. Fixes to ObjectTracking
5. Added CropNode

are these the changes that i need to look at merging?

Notes on the above:

### WithinRange HSV support + HSV color formats

https://github.com/smakhtin/VVVV.Packs.Image/commit/005ba36fa711312c6f2cb8762634d7dc1252f6c9
looks good to me.

https://github.com/smakhtin/VVVV.Packs.Image/commit/0a4bb82459bd761486772452b783451aabd350bf
Not sure why all the CMPNode's are in the InRange.cs file. Will look into this.

## Normalised range support

I presume that there should be an Enum pin for 'number format' being either 'Normalised' or 'Raw'
An example of Raw usage is the User ID image from OpenNI (you want to check strictly against raw values like 0, 1, 2, etc) or using WithinRange with the Depth image (Raw would refer to mm, Normalised would just be pretty crazy).

But I can see that Normalised is going to make sense for a vast set of use cases

## ObjectTracking and CropNode

Will test and merge

**Comment by elliotwoods** [comment]
OK. this is the last issue before the final alpha release
then will begin working on beta

will look at this tomorrow. dinner time now...

**Comment by smakhtin** [comment]
About features set, yes, you are correct i think. 

In vvvv community i think it's common to have various node version with similar code base in one file, because only vvvv input interfaces is changing.

About normalized stuff, let's make a hidden toggle (Inspector only), that just disabling normalization and allows you to pass RAW values.

**Comment by elliotwoods** [comment]
hey
i've been looking into this
and it's going to be super tricky for me to cherry pick through this to get it to merge
is there any way that you can split this into seperate feature branch PR's?

i,e,:
1. Make local branches on your computer which mirror the current repo master
2. Cherry pick in the changes for each feature branch and make PR's per feature branch

note that the following changes have been made:
1. Generally 'OpenCV' has been replaced for 'CV'
2. NuGet is now used to manage References (rather than referencing dll's in vvvv folder)
3. Some nodes have changed names
4. the 'lib' folder has been removed (and all contents from it are now in the root). this is to retain compatability with the normal packs model (required for future Factory use).

**Comment by smakhtin** [comment]
Ok, i will make a separate PR. I currently in a deadline, so can finish this around December 8-10.

**Comment by smakhtin** [comment]
If i understand right, everything is merged right now, besides my small filter fixes. Can you close this and pull latest commit from my range branch?

**Pull request closed without merging**
