### PR TITLE
minor stuff

### PR DESCRIPTION
**Pull request by joreg**
added missing modules, fixes for helppatches and naming fixes in \StereoCalibrate patches
essentially the stuff i added for the pack release http://vvvv.org/contribution/vvvv.packs.image

and now fixed 2 references in CalibrateProjectorKinect and added the missing WaitForCalm (Animation) module

### CODE REVIEW

**Comment by circuitb** [comment]
hi,
Reader / Writer (OpenCV intrinsics) is missing
also i think  the VVVV.Nodes.SpreadTableValue.dll should be included in the ImagePack!

**Comment by joreg** [comment]
where is that missing?

**Comment by circuitb** [comment]
SolvePnP (OpenCV) help.v4p

**Comment by circuitb** [comment]
there's also a wrong path for World.fx in WorldAndNormals (OpenNI).v4p

**Comment by joreg** [comment]
ok. those Reader/Writers will then be there with the next release. i'll not change that patch for now. 

the World.fx is indeed missing. would need @elliotwoods to add that

**Comment by circuitb** [comment]
just forgot to mention !  the current
VVVV.Nodes.OpenCV.OpenNI.dll is 16ko and doesn't include the
Context (OpenCV OpenNI) and Image (OpenCV OpenNI)  nodes!!!
the working one for me is 18ko!

**Comment by joreg** [comment]
@circuitb for now i didn't change any binaries in the pack for download via contributions. i only added missing stuff and reorganized the directory layout so it resembles a proper pack.

**Comment by elliotwoods** [comment]
hey!
thanks for the fixes Joreg

@circuitb - TableBuffer will come back via Addonpack in the near future

WaitForCalm might die off since it doesn't really belong in the ImagePack, and Joreg notes that there is an alternative in the AddonPack already

Intrinsics Reader-Writers are at
https://github.com/elliotwoods/VVVV.Packs.Image/tree/master/src/nodes/plugins/Image/OpenCV/src/Calibration

**Comment by elliotwoods** [comment]
World.fx? is that the old method where we go depth->world?
i've stopped doing that as you get much more accurate World results getting OpenNI (or MS) to do the transformation for you.

**Comment by joreg** [comment]
re: World.fx in WorldAndNormals (OpenNI).v4p
@elliotwoods you should be the one to know that. if no longer needed is suggest to just remove that whole module then

**Comment by circuitb** [comment]
@elliotwoods  wow  just discovered you create an AsImage (OpenCV DX11.Texture2D)!!!!
  so for calibration process  we don't need the openCV openNI nodes anymore!
does the perf with  findBoards are good?

**Comment by elliotwoods** [comment]
ok. will look into this PR (ignoring World and OpenNI issues should come out in the wash over the next couple of days so I might resolve this thread before looking into those bits).

Some notes:
- The camera preview node I think belongs in the Addonpack as it working for projectors, cameras (both physical and virtual). 
- What is the node by @woeishi which could remove the need for WaitForCalm?
- There's a few things in this PR which don't seem to belong (edits to structured light help patches, SolvePnP help). I'm going to merge via a local branch (i.e. not use the 'merge' button here to keep it all clean).

**Comment by elliotwoods** [comment]
@circuitb  - i haven't done any perf testing with DX11 AsImage sorry.
i might get a chance to have a look later this week.

**Comment by joreg** [comment]
"There's a few things in this PR which don't seem to belong (edits to structured light help patches, SolvePnP help)."
nono, thats exactly what this PR is about: cleanup
it is only about fixing dead references, adding missing modules, fixing helppatches. no functional changes at all. 
that is the state which is in the current imagepack release when you download it. 

and ja, easily ignore world and openni stuff as brought up by circuitb, they are unrelated to this initial PR

**Comment by elliotwoods** [comment]
ok i see.
will merge now and an issue that Camera preview and WaitForCalm might be duplicated and should be checked before beta release.

**Pull request merged**
