### PR TITLE
updated nugets for beta34.2 and raised target framework to 4.5

### PR DESCRIPTION
**Pull request by sebllll**
just updated all the stuff so it's up to date... only thing that didn't compile is the flyCapture project. i guess flycapture2managed.dll is compiled for .net 4.0 ... anyway, this project was unloaded in the master branch so i guessed it's not so important or even used by anyone.

### CODE REVIEW

**Comment by elliotwoods** [comment]
Hey.
Great to see this!
I know some people are actually relying on the FlyCapture implementation. So maybe they're using an old branch.
if I can get you an up to date dll, can you add it to the pack again?

Elliot

**Comment by sebllll** [comment]
hi elliot,

yes, i'm not registered at pointgrey, so can't check if there's a new version available. if you can get one, i think it'll not be to hard to add it again. maybe you can attach it here somehow and i'll integrate it then.

**Comment by smakhtin** [comment]
About Pointgrey NuGet package - not so long ago i was contacted by they legal department and they asked me to remove my Pointgrey package from public NuGet listing. In future, i think we need a private server for this.

**Comment by sebllll** [comment]
arg, that's a pity, a nuget would be the best for everyone... i can't understand why companies act like this.

but i guess it's ok to have a dll in the repo? if yes, we should ship it like the emgucv ones.

**Comment by sebllll** [comment]
ok guys, what shall we do now? is anyone registered at pointgrey and can provide a proper dll? ideally in x64 and x86 or anycpu flavour...

**Comment by elliotwoods** [comment]
Did I add you as a repo admin?
Or do you prefer to use your own fork?

I noticed you updated the version on the contributions section.
Thank you for that!

**Comment by YanYas** [comment]
Hi,
I tried Sebllll's branch with a but I get the following error:

> `The primary reference "FeralTic, Version=1.0.0.0, Culture=neutral, processorArchitecture=x86" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0". (MSB3274) - C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets:1697,5`

I guess this means the nature of the FeralTic reference needs to be updated still?

(Edit) I'm using a build of DX11 from github rather that NuGet

**Comment by sebllll** [comment]
closing this one because it's out of date. here's a new attempt https://github.com/elliotwoods/VVVV.Packs.Image/pull/75

**Pull request closed without merging**
