### PR TITLE
Added AsDX11TextureNode and fixed ObjectTracker

### PR DESCRIPTION
**Pull request by smakhtin**
Looks like we have a strange conflicts in line endings. Test it on separate branch.

### CODE REVIEW

**Comment by elliotwoods** [comment]
hey!
sorry for slow uptake on this

from your description i've merged the relevant files.
the pull request is for 58 files changed, which is somehow wrong (there seems to be changes all over the place)

i think we've both edited the VideoIn node at the same time so i've kept my own code here.
could you test this / try and merge?

**Comment by elliotwoods** [comment]
i have merged this manually and pushed to my master branch
please try to be in sync with that branch
atomic pull requests are great (e.g. 1 for dx11 texture, 1 for crop node, etc).

**Comment by elliotwoods** [comment]
perhaps you could check the diff between my master and your master
i use TortoiseGit for diff.

**Comment by elliotwoods** [comment]
also i didn't include your paths to DX11 in the solution yet, as vux hasn't noted where we're supposed to locate the DX11 project files relative to VVVV.

**Comment by smakhtin** [comment]
Yeah, currently all this path thing is really messy. Ok, i will check for differences between branches. What do you think about DX11 dependency? Should we extract all related code into separate repo or keep in one? I think DX11 should become essential in near future, so keeping it as core dependency is not so bad. I currently using DX9 only as legacy solution, when can't find something in DX11. Maybe we should start just separate DX11 branch for this? In this case we can rewrite all old DX9 helpers for DX11 support, add some new shaders etc.

**Pull request closed without merging**
