### PR TITLE
Fixed https://github.com/elliotwoods/VVVV.Packs.Image/issues/38

### PR DESCRIPTION
**Pull request by azeno**
- Updated VVVV.\* nuget packages
- Added new package dependency to VVVV.Nodes.Generic
- Re-enabled Cons (CV.Image) node

### CODE REVIEW

**Comment by azeno** [comment]
thank you. fixed now.

**Comment by smakhtin** [comment]
I'm testing right now Emgu.CV assemblies bug, if i remember, everything should be copied automatically. So there is no need to allow VS driven copying process, i made a script for this.

UPD: @azeno you are right, i forget to chage this flag to true. Thanks everyone for fixing my bugs.

**Comment by elliotwoods** [comment]
thanks everyone for working on this

**Comment by Jaryn91** [comment]
Damn. It doesn't works for me ;(.

**Pull request merged**
